name: run-test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: code-setup
              uses: actions/checkout@v3
            - name: install-node
              uses: actions/setup-node@v3
              with: 
                node-version: 16
            - name: install dependency
              run: npm ci
            - name: run-test
              run: npm test
            - name: cleaning
              run: echo "Run Success"